prometheus:
  ingress:
    enabled: true
    pathType: Prefix
    hosts:
      - prometheus.k8s.sikademo.com # --- PROMETHEUS DOMAIN ---
    paths:
      - /

grafana:
  ingress:
    enabled: true
    pathType: Prefix
    annotations: {}
    hosts:
      - grafana.k8s.sikademo.com # --- GRAFANA DOMAIN ---
    paths:
      - /

alertmanager:
  ingress:
    enabled: true
    pathType: Prefix
    annotations: {}
    hosts:
      - alertmanager.k8s.sikademo.com # --- ALERTMANAGER DOMAIN ---
    paths:
      - /
