apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: eck
  namespace: elastic-stack
spec:
  version: 7.8.0
  count: 1
  elasticsearchRef:
    name: elk
  http:
    tls:
      selfSignedCertificate:
        disabled: true
